'use server';

/**
 * @fileOverview An AI agent to test prompts in a playground environment.
 *
 * - testPrompt - A function that allows users to test prompts with the OpenAI API.
 * - TestPromptInput - The input type for the testPrompt function, including the prompt text.
 * - TestPromptOutput - The return type for the testPrompt function, providing the LLM response.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TestPromptInputSchema = z.object({
  promptText: z.string().describe('The prompt text to be tested.'),
});
export type TestPromptInput = z.infer<typeof TestPromptInputSchema>;

const TestPromptOutputSchema = z.object({
  llmResponse: z.string().describe('The response generated by the LLM for the given prompt.'),
});
export type TestPromptOutput = z.infer<typeof TestPromptOutputSchema>;

export async function testPrompt(input: TestPromptInput): Promise<TestPromptOutput> {
  return testPromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'testPromptPrompt',
  input: {schema: TestPromptInputSchema},
  output: {schema: TestPromptOutputSchema},
  prompt: `{{{promptText}}}`,
});

const testPromptFlow = ai.defineFlow(
  {
    name: 'testPromptFlow',
    inputSchema: TestPromptInputSchema,
    outputSchema: TestPromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
